name: build-installer

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'develop'
        options:
          - 'main'
          - 'staging'
          - 'develop'

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest ]
        python-version: [ 3.11 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          repository: uPtt-messenger/backend
          path: backend

      - name: Cache backend build
        uses: actions/cache@v4
        id: cache-backend-build
        with:
          path: backend/build-packages
          key: ${{ runner.os }}-backend-build-${{ hashFiles('backend/**') }}
          restore-keys: |
            ${{ runner.os }}-backend-build-

      - name: Set up Python
        if: steps.cache-backend-build.outputs.cache-hit != 'true'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Generate requirements.txt
        if: steps.cache-backend-build.outputs.cache-hit != 'true'
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install poetry poetry-plugin-export
          poetry export -f requirements.txt --output requirements.txt

      - name: Install dependencies
        if: steps.cache-backend-build.outputs.cache-hit != 'true'
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install Nuitka

      - name: Build backend
        if: steps.cache-backend-build.outputs.cache-hit != 'true'
        working-directory: backend
        run: |
          if [ ${{ matrix.os }} == 'macos-latest' ]; then
              ./build.sh build
          else
              ./build.bat build
          fi

      - name: Build app
        if: ${{ matrix.os }} == 'macos-latest'
        run: |
          cp -r installer/uPtt.app .
          cp -r backend/build-packages/* uPtt.app/Contents/MacOS
          ls -lR uPtt.app
          zip -r uPtt-MacOS.zip uPtt.app

      - name: Upload artifact
        if: ${{ matrix.os }} == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: uPtt-MacOS
          path: uPtt-MacOS.zip