name: Build installer

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'develop'
        options:
          - 'main'
          - 'staging'
          - 'develop'

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest ]
        python-version: [ 3.11 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          repository: uPtt/backend
          path: backend

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Generate requirements.txt
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install poetry poetry-plugin-export
          poetry export -f requirements.txt --output requirements.txt

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install Nuitka

      - name: Build backend
        working-directory: backend
        run: |
          if [ ${{ matrix.os }} == 'macos-latest' ]; then
              ./build.sh build
          else
              ./build.bat build
          fi

      - name: Build installer
        if: ${{ matrix.os }} == 'macos-latest'
        working-directory: backend
        run: |
          # Create a bundle
          mkdir -p uPtt.app/Contents/MacOS
          cp -r build/uptt_backend.dist/* uPtt.app/Contents/MacOS
          cp -r build/uptt_mq_server.dist/* uPtt.app/Contents/MacOS
          
          cp 

