
name: docs

# run on merge to master or manual trigger
on:
  pull_request:
    types: [ closed ]
  workflow_dispatch:

jobs:
  build:
    name: Build doc and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v5
      with:
          python-version: 3.11
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Generate requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install poetry poetry-plugin-export
        poetry export -f requirements.txt --output docs/requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt
    - name: Install graphviz
      run: |
        sudo apt-get install graphviz
    - name: Build and Commit
      uses: sphinx-notes/pages@v2
      with:
        requirements_path: docs/requirements.txt
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        branch: gh-pages